name: Build LaTeX CV

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex

      - name: Copy PDF to docs/
        run: |
          mkdir -p docs
          cp cv.pdf docs/

      - name: Commit and push PDF to docs/
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/cv.pdf || echo "Nothing to add"
          git commit -m "Update compiled CV" || echo "Nothing to commit"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push || echo "Nothing to push"
